---
name: Lint and test program
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # DevOps
      - name: Getting DevOps CV codebase
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - run: echo Hello world
